@startuml SecuenciaCrearTask
title Secuencia 1 - Crear Task usando Factory Method + TaskManager (Singleton)

actor Usuario as U
participant ":MainMenu" as menu
participant ":AtomicInteger" as ids
participant ":TaskFactory" as factory
participant ":Task" as task
participant ":User" as user
participant ":TaskManager" as manager

U -> menu : opcion "1. Crear Task"
activate menu

menu -> ids : getAndIncrement()
activate ids
ids --> menu : nextId
deactivate ids

menu -> factory : createItem(nextId, title, desc, HIGH, owner)
activate factory
note right of factory
  Factory Method:
  TaskFactory decide instanciar Task
  (cliente no usa "new" directamente)
end note

factory -> task : new Task(nextId, title, desc, HIGH, owner)
activate task
task -> task : status = PENDING
task -> task : collaborators = synchronizedList()
task -> task : observers = synchronizedList()
task --> factory : task
deactivate task

factory --> menu : task
deactivate factory

menu -> user : addItem(task)
activate user
user -> user : createdItems.add(task)
user --> menu : true
deactivate user

menu -> manager : getInstance()
activate manager
note right of manager
  Singleton thread-safe:
  double-checked locking
  con volatile + MUTEX
end note
manager --> menu : instance
deactivate manager

menu -> manager : addTask(task)
activate manager
manager -> manager : lock.lock()
manager -> manager : tasks.put(task.id, task)
manager -> manager : lock.unlock()  (finally)
manager --> menu : void
deactivate manager

menu --> U : "Task creada con ID " + task.getId()
deactivate menu

@enduml
